// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANPq1R2x83iE6OVMP2B8AuQQ4vl-i8zMk',
    appId: '1:1062158820259:web:a080be2ebd43feb6e43016',
    messagingSenderId: '1062158820259',
    projectId: 'hsmarthome-5df28',
    authDomain: 'hsmarthome-5df28.firebaseapp.com',
    storageBucket: 'hsmarthome-5df28.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsR_6Ym65lJDG1K_xgoZbPKDmw1L5yruc',
    appId: '1:1062158820259:android:50106d4f72c87ec2e43016',
    messagingSenderId: '1062158820259',
    projectId: 'hsmarthome-5df28',
    storageBucket: 'hsmarthome-5df28.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBu1wIywzgqP1Ibm-T13bUHn5hBZwH1vpM',
    appId: '1:1062158820259:ios:58aa9f786b89a9aee43016',
    messagingSenderId: '1062158820259',
    projectId: 'hsmarthome-5df28',
    storageBucket: 'hsmarthome-5df28.appspot.com',
    androidClientId: '1062158820259-jrl7upick8e43ktbvdt8av65lgdt5ka2.apps.googleusercontent.com',
    iosClientId: '1062158820259-iutfs5m2qtqlmmundfvdc9m05lfs17qe.apps.googleusercontent.com',
    iosBundleId: 'com.example.hsmarthome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBu1wIywzgqP1Ibm-T13bUHn5hBZwH1vpM',
    appId: '1:1062158820259:ios:58aa9f786b89a9aee43016',
    messagingSenderId: '1062158820259',
    projectId: 'hsmarthome-5df28',
    storageBucket: 'hsmarthome-5df28.appspot.com',
    androidClientId: '1062158820259-jrl7upick8e43ktbvdt8av65lgdt5ka2.apps.googleusercontent.com',
    iosClientId: '1062158820259-iutfs5m2qtqlmmundfvdc9m05lfs17qe.apps.googleusercontent.com',
    iosBundleId: 'com.example.hsmarthome',
  );
}
