// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBC_xo5jgikh2oPw7DC8FwOpBZRHawdOJM',
    appId: '1:431003137592:web:e8b02e44d27eb51e2ed8cd',
    messagingSenderId: '431003137592',
    projectId: 'hsmarthome-firebase',
    authDomain: 'hsmarthome-firebase.firebaseapp.com',
    storageBucket: 'hsmarthome-firebase.appspot.com',
    measurementId: 'G-QEXMV95T1K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5DgSToafiTjRNRqz2MovlWIpr4GwLKLU',
    appId: '1:431003137592:android:eb4d1e110902ed0b2ed8cd',
    messagingSenderId: '431003137592',
    projectId: 'hsmarthome-firebase',
    storageBucket: 'hsmarthome-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLMb8UtBxYGeQBlJd-hzTTXjZjtJrgQn4',
    appId: '1:431003137592:ios:81da7079ee7aa14f2ed8cd',
    messagingSenderId: '431003137592',
    projectId: 'hsmarthome-firebase',
    storageBucket: 'hsmarthome-firebase.appspot.com',
    androidClientId: '431003137592-27oefb82tai8lknnjfkjsmi0vlrpt1nf.apps.googleusercontent.com',
    iosClientId: '431003137592-s6m3ui2k63i2nmj4g1dtel9v9juqbd3n.apps.googleusercontent.com',
    iosBundleId: 'com.example.hsmarthome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLMb8UtBxYGeQBlJd-hzTTXjZjtJrgQn4',
    appId: '1:431003137592:ios:81da7079ee7aa14f2ed8cd',
    messagingSenderId: '431003137592',
    projectId: 'hsmarthome-firebase',
    storageBucket: 'hsmarthome-firebase.appspot.com',
    androidClientId: '431003137592-27oefb82tai8lknnjfkjsmi0vlrpt1nf.apps.googleusercontent.com',
    iosClientId: '431003137592-s6m3ui2k63i2nmj4g1dtel9v9juqbd3n.apps.googleusercontent.com',
    iosBundleId: 'com.example.hsmarthome',
  );
}
